CREATE PROCEDURE GetAllUserTables
AS
BEGIN
    SELECT 
        TABLE_NAME AS TableName,
        TABLE_SCHEMA AS SchemaName,
        'TABLE' AS ObjectType
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'BASE TABLE'
      AND TABLE_NAME NOT LIKE 'sys%'
      AND TABLE_NAME NOT LIKE 'INFORMATION_SCHEMA%'
END
