-- CREATE PROCEDURE GetAuditLogs
--     @p_user_filter NVARCHAR(100) = NULL,
--     @p_date_from   DATETIME      = NULL
-- AS
-- BEGIN
--     SET NOCOUNT ON;

--     IF @p_user_filter IS NOT NULL
--     BEGIN
--         DECLARE @JsonValidation NVARCHAR(MAX) = (SELECT @p_user_filter AS [UserName] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER);

--         EXEC ValidateColumnData @TableName = 'AuditLog', @JsonValues = @JsonValidation;
--     END

--     SELECT 
--         ChangeDate AS actionDate,
--         Action     AS operation,
--         TableName  AS tableName,
--         RecordId   AS recordId,
--         UserName   AS updateUser,
--         Reason     AS reason,
--         NewValues  AS updatedData
--     FROM 
--         AuditLog
--     WHERE 
--         (@p_user_filter IS NULL OR UserName = @p_user_filter)
--         AND (@p_date_from IS NULL OR ChangeDate >= @p_date_from)
--     ORDER BY 
--         ChangeDate DESC;
-- END
-- GO