CREATE PROCEDURE dbo.GetColumnsForTable
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        t.TABLE_SCHEMA AS SchemaName,
        t.TABLE_NAME AS TableName,
        c.COLUMN_NAME AS ColumnName,
        c.DATA_TYPE AS DataType,
        c.IS_NULLABLE AS IsNullable,
        c.CHARACTER_MAXIMUM_LENGTH AS MaxLength
    FROM INFORMATION_SCHEMA.COLUMNS c
    INNER JOIN INFORMATION_SCHEMA.TABLES t
        ON c.TABLE_NAME = t.TABLE_NAME
        AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
    ORDER BY t.TABLE_SCHEMA, t.TABLE_NAME, c.ORDINAL_POSITION;
END
